# fly.toml app configuration file generated for nsw-drivers-toolbox on 2023-11-04T23:57:20+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nsw-drivers-toolbox"
primary_region = "syd"

[build]
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
